feature_flags:
  dev_auth:
    local: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    development: true
    uat: true
    production: false # must never be enabled in the live service
  postal_evidence:
    local: <%= ENV.fetch("POSTAL_EVIDENCE", false) %>
    development: false
    uat: false
    production: false
  insights:
    local: <%= ENV.fetch("INSIGHTS_ENABLED", false) %>
    development: true
    uat: true
    production: true
  nsm_insights:
    local: <%= ENV.fetch("NSM_INSIGHTS_ENABLED", false) %>
    development: true
    uat: true
    production: true
  search:
    local: <%= ENV.fetch("SEARCH", true) %>
    development: true
    uat: true
    production: true
  nsm_rfi_loop:
    local: <%= ENV.fetch("NSM_RFI", true) %>
    development: true
    uat: true
    production: false

