# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  app: 4
  worker: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: "laa-assess-crime-forms-app"
fullnameOverride: "laa-assess-crime-forms-app"

service:
  type: ClusterIP
  port: 80
  internalPort: 3000
  workerPort: 7433

ingress:
  enabled: true
  namespace: laa-assess-crime-forms-uat
  className: modsec
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-assess-crime-forms-app-laa-assess-crime-forms-uat-green
  hosts:
    - host: uat.assess-crime-forms.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
          service:
            name: laa-assess-crime-forms-uat
            port:
              number: 3000

  tls:
    - hosts:
      - uat.assess-crime-forms.service.justice.gov.uk
      secretName: laa-assess-crime-forms-cert

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 500Mi

variables:
  environment: uat
  appStoreUrl: http://laa-crime-application-store-app.laa-crime-application-store-uat.svc.cluster.local
  enableSyncTriggerEndpoint: 'false'
  allowIndexing: 'false'

service_account:
  name: laa-assess-crime-forms-uat-irsa

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: [ "ALL" ]

# Instead of a temporary postgres pod we use RDS
postgresql:
  enabled: false

# Instead of a temporary redis pod we use Elasticache
redis:
  enabled: false

metabase:
  dashboardIds: 'TBC'
  siteUrl: 'https://uat.crime-forms-metabase.service.justice.gov.uk'
