# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  app: 4
  worker: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: "laa-assess-crime-forms-app"
fullnameOverride: "laa-assess-crime-forms-app"

service:
  type: ClusterIP
  port: 80
  internalPort: 3000
  workerPort: 7433

ingress:
  enabled: true
  namespace: laa-assess-crime-forms-prod
  className: modsec
  modsec:
    ruleState: "On"
    auditState: "RelevantOnly"
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-assess-crime-forms-app-laa-assess-crime-forms-prod-green
  hosts:
    - host: assess-crime-forms.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
          service:
            name: laa-assess-crime-forms-prod
            port:
              number: 3000

  tls:
    - hosts:
      - assess-crime-forms.service.justice.gov.uk
      secretName: laa-assess-crime-forms-cert

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 500Mi

variables:
  environment: production
  appStoreUrl: http://laa-crime-application-store-app.laa-crime-application-store-production.svc.cluster.local
  enableSyncTriggerEndpoint: 'false'
  allowIndexing: 'true'

service_account:
  name: laa-assess-crime-forms-prod-irsa

# Instead of a temporary postgres pod we use RDS
postgresql:
  enabled: false

# Instead of a temporary redis pod we use Elasticache
redis:
  enabled: false

metabase:
  priorAuthorityDashboardIds: '3,2'
  nsmDashboardIds: '4'
  siteUrl: 'https://crime-forms-metabase.service.justice.gov.uk'

customErrorService:
  enabled: true
